INSERT INTO opm.payment_reversal_reason(id, deleted, name) VALUES(1, false, 'Applied to wrong account');
INSERT INTO opm.payment_reversal_reason(id, deleted, name) VALUES(2, false, 'Bank Account Closed');
INSERT INTO opm.payment_reversal_reason(id, deleted, name) VALUES(3, false, 'Data Entry Error');
INSERT INTO opm.payment_reversal_reason(id, deleted, name) VALUES(4, false, 'No Acct/Cannot Locate');
INSERT INTO opm.payment_reversal_reason(id, deleted, name) VALUES(5, false, 'Noon-Sufficient Funds');
INSERT INTO opm.payment_reversal_reason(id, deleted, name) VALUES(6, false, 'Stop Payment');

INSERT INTO opm.calculation_status(id, deleted, name) VALUES(1, false, 'Success');
INSERT INTO opm.calculation_status(id, deleted, name) VALUES(2, false, 'Failed');
INSERT INTO opm.calculation_status(id, deleted, name) VALUES(3, false, 'Calculation Saved');
INSERT INTO opm.calculation_status(id, deleted, name) VALUES(4, false, 'Calculation');
INSERT INTO opm.calculation_status(id, deleted, name) VALUES(5, false, 'Calculation Triggered Pending');

INSERT INTO opm.service_type(id, deleted, name) VALUES(1, false, 'GS');
INSERT INTO opm.service_type(id, deleted, name) VALUES(2, false, 'WAGE GRADE');
INSERT INTO opm.service_type(id, deleted, name) VALUES(3, false, 'ES-Executive Schedule');
INSERT INTO opm.service_type(id, deleted, name) VALUES(4, false, 'SES-Senior Executive Schedule');
INSERT INTO opm.service_type(id, deleted, name) VALUES(5, false, 'Senior Official');
INSERT INTO opm.service_type(id, deleted, name) VALUES(6, false, 'Legislators');
INSERT INTO opm.service_type(id, deleted, name) VALUES(7, false, 'Legislators- SS Max');
INSERT INTO opm.service_type(id, deleted, name) VALUES(8, false, 'Postal Service- PTF');
INSERT INTO opm.service_type(id, deleted, name) VALUES(9, false, 'Postal Service- LT (and FT)');
INSERT INTO opm.service_type(id, deleted, name) VALUES(10, false, 'Legislative Employee');
INSERT INTO opm.service_type(id, deleted, name) VALUES(11, false, 'Senate Child Care');
INSERT INTO opm.service_type(id, deleted, name) VALUES(12, false, 'Library of Congress Child Care');
INSERT INTO opm.service_type(id, deleted, name) VALUES(13, false, 'Legislative Employee- SS Max');
INSERT INTO opm.service_type(id, deleted, name) VALUES(14, false, 'DC GOVERNMENT');
INSERT INTO opm.service_type(id, deleted, name) VALUES(15, false, 'FIREFIGHTER');
INSERT INTO opm.service_type(id, deleted, name) VALUES(16, false, 'Air Traffic Controller');
INSERT INTO opm.service_type(id, deleted, name) VALUES(17, false, 'Law Enforcement');
INSERT INTO opm.service_type(id, deleted, name) VALUES(18, false, 'Capitol Police');
INSERT INTO opm.service_type(id, deleted, name) VALUES(19, false, 'Customs Border Prot Officer');
INSERT INTO opm.service_type(id, deleted, name) VALUES(20, false, 'Supreme Ct Police');
INSERT INTO opm.service_type(id, deleted, name) VALUES(21, false, 'Bankruptcy Judge');
INSERT INTO opm.service_type(id, deleted, name) VALUES(22, false, 'Bankruptcy Judge- SS Max');
INSERT INTO opm.service_type(id, deleted, name) VALUES(23, false, 'Ct of Fed Claims');
INSERT INTO opm.service_type(id, deleted, name) VALUES(24, false, 'Ct of Fed Claims- SS Max');
INSERT INTO opm.service_type(id, deleted, name) VALUES(25, false, 'Military Appeals Judge');
INSERT INTO opm.service_type(id, deleted, name) VALUES(26, false, 'Military Appeals Judge- SS Max');
INSERT INTO opm.service_type(id, deleted, name) VALUES(27, false, 'US Magistrate');
INSERT INTO opm.service_type(id, deleted, name) VALUES(28, false, 'US Magistrate- SS Max');
INSERT INTO opm.service_type(id, deleted, name) VALUES(29, false, 'Reemployed Offset');
INSERT INTO opm.service_type(id, deleted, name) VALUES(30, false, 'Reemployed Offset- SS Max');
INSERT INTO opm.service_type(id, deleted, name) VALUES(31, false, 'Title 38 USC');
INSERT INTO opm.service_type(id, deleted, name) VALUES(32, false, 'Foreign Service Schedule');
INSERT INTO opm.service_type(id, deleted, name) VALUES(33, false, 'Federal Reserve Official');
INSERT INTO opm.service_type(id, deleted, name) VALUES(34, false, 'Nuclear Materials Courier');
INSERT INTO opm.service_type(id, deleted, name) VALUES(35, false, 'PEACE CORPS/VISTA');
INSERT INTO opm.service_type(id, deleted, name) VALUES(36, false, 'UNKNOWN');
INSERT INTO opm.service_type(id, deleted, name) VALUES(37, false, 'CAREER');
INSERT INTO opm.service_type(id, deleted, name) VALUES(38, false, 'POSTAL PART TIME FLEX');
INSERT INTO opm.service_type(id, deleted, name) VALUES(39, false, 'POSTAL LIMITED TOUR');
INSERT INTO opm.service_type(id, deleted, name) VALUES(40, false, 'FSPS-LEO/FF');
INSERT INTO opm.service_type(id, deleted, name) VALUES(41, false, 'Not Applicable');

INSERT INTO opm.claim_officer(id, deleted, name) VALUES(1, false, 'Jeffrey Kelley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(2, false, 'Terry Larson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(3, false, 'Laura Mitchell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(4, false, 'Eugene Hudson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(5, false, 'Brian Scott');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(6, false, 'Karen Bailey');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(7, false, 'Stephanie Perry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(8, false, 'Howard Lynch');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(9, false, 'Roy Wheeler');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(10, false, 'Betty Hunter');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(11, false, 'Paul Lawrence');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(12, false, 'Michelle Black');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(13, false, 'Tina Howard');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(14, false, 'Julie Butler');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(15, false, 'Catherine Woods');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(16, false, 'Brandon Ferguson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(17, false, 'Nancy Perez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(18, false, 'George Howard');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(19, false, 'Jean Phillips');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(20, false, 'Peter Flores');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(21, false, 'Karen Day');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(22, false, 'Joan Watkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(23, false, 'Helen Reynolds');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(24, false, 'Adam Long');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(25, false, 'Richard Scott');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(26, false, 'Kevin Cunningham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(27, false, 'Richard Collins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(28, false, 'Louis Jordan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(29, false, 'Antonio Hudson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(30, false, 'Louise Bishop');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(31, false, 'Harry Bowman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(32, false, 'Joe Murray');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(33, false, 'Pamela Ferguson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(34, false, 'Walter Frazier');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(35, false, 'Johnny Garrett');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(36, false, 'Andrew Knight');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(37, false, 'Wanda Gardner');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(38, false, 'Keith Lewis');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(39, false, 'Earl Cooper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(40, false, 'Anthony Vasquez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(41, false, 'David Allen');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(42, false, 'Joan Bennett');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(43, false, 'Ruby Cruz');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(44, false, 'Patricia Nelson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(45, false, 'Jerry West');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(46, false, 'Ralph Medina');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(47, false, 'Kelly Sullivan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(48, false, 'Arthur Lawson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(49, false, 'Martha Powell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(50, false, 'Ronald Campbell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(51, false, 'Jesse Black');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(52, false, 'Ruth Nichols');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(53, false, 'Lillian Cunningham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(54, false, 'Arthur Perez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(55, false, 'Sean Howell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(56, false, 'Janice Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(57, false, 'Kenneth Webb');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(58, false, 'Doris Sullivan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(59, false, 'Dorothy Lawson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(60, false, 'Elizabeth Medina');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(61, false, 'Larry Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(62, false, 'Carlos Thompson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(63, false, 'Daniel George');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(64, false, 'Alan Phillips');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(65, false, 'Donna Parker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(66, false, 'Catherine Wright');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(67, false, 'Tina Reyes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(68, false, 'Marie Hamilton');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(69, false, 'Janet Kelley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(70, false, 'Brian Harper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(71, false, 'Randy Green');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(72, false, 'Lillian Alvarez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(73, false, 'Carlos Harper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(74, false, 'Marie Gonzalez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(75, false, 'Denise Rogers');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(76, false, 'George Bryant');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(77, false, 'Aaron Knight');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(78, false, 'Judith Moreno');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(79, false, 'Daniel Richards');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(80, false, 'Louis Jacobs');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(81, false, 'Mark Peters');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(82, false, 'Billy Morris');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(83, false, 'Sarah Peters');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(84, false, 'Juan Smith');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(85, false, 'Carol Frazier');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(86, false, 'Kathryn Palmer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(87, false, 'Marie Harper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(88, false, 'Phillip Matthews');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(89, false, 'Nicholas Cruz');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(90, false, 'Marie Rose');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(91, false, 'Roy Reid');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(92, false, 'Julie West');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(93, false, 'Russell Powell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(94, false, 'Raymond Martin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(95, false, 'Steven Chapman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(96, false, 'Gloria Garcia');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(97, false, 'Jacqueline Perry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(98, false, 'Fred Berry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(99, false, 'Donna Harper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(100, false, 'Lois Cox');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(101, false, 'Theresa Pierce');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(102, false, 'Robin Ward');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(103, false, 'Charles Reyes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(104, false, 'Robin Cunningham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(105, false, 'Kelly Cunningham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(106, false, 'George Frazier');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(107, false, 'Eric Austin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(108, false, 'Michelle Fisher');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(109, false, 'Sandra Andrews');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(110, false, 'Amy Porter');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(111, false, 'Brandon Long');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(112, false, 'Keith Lee');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(113, false, 'Rachel Harvey');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(114, false, 'Brenda Reyes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(115, false, 'Richard Parker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(116, false, 'Tammy Ross');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(117, false, 'Willie Cox');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(118, false, 'Steve Johnston');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(119, false, 'Gary Taylor');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(120, false, 'Jack Mcdonald');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(121, false, 'Antonio Evans');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(122, false, 'Virginia Riley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(123, false, 'Fred Powell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(124, false, 'Edward Wheeler');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(125, false, 'Cheryl Austin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(126, false, 'Carl Andrews');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(127, false, 'Phyllis Kelly');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(128, false, 'Timothy Richards');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(129, false, 'Teresa Gilbert');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(130, false, 'Diana Andrews');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(131, false, 'Theresa Willis');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(132, false, 'Roger Williams');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(133, false, 'Nancy Watkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(134, false, 'Peter Daniels');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(135, false, 'Norma Spencer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(136, false, 'Kenneth Fields');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(137, false, 'Lawrence Carr');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(138, false, 'Henry Kelley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(139, false, 'Deborah Lane');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(140, false, 'Andrea Taylor');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(141, false, 'Randy Jacobs');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(142, false, 'Jane Olson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(143, false, 'Sara Holmes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(144, false, 'Jesse Richardson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(145, false, 'Craig Alexander');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(146, false, 'Keith Wood');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(147, false, 'Janet Gardner');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(148, false, 'Martin Nichols');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(149, false, 'Martin Lawson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(150, false, 'Jack Tucker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(151, false, 'Rachel Mason');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(152, false, 'Roger Cunningham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(153, false, 'Willie Hughes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(154, false, 'Joyce Fisher');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(155, false, 'Donald Smith');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(156, false, 'Ruth Griffin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(157, false, 'Tina Richardson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(158, false, 'Donald Ford');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(159, false, 'Helen Roberts');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(160, false, 'Lois Olson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(161, false, 'Thomas Garza');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(162, false, 'Gary Payne');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(163, false, 'Linda Castillo');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(164, false, 'Gloria Moreno');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(165, false, 'Harold Welch');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(166, false, 'Daniel Lynch');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(167, false, 'Judy James');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(168, false, 'Frances Cox');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(169, false, 'Johnny Grant');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(170, false, 'Jimmy Romero');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(171, false, 'Rachel Jordan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(172, false, 'Donna Payne');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(173, false, 'Anne Stephens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(174, false, 'Denise Cox');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(175, false, 'Phyllis Diaz');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(176, false, 'Henry Morgan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(177, false, 'Earl Greene');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(178, false, 'Dorothy Shaw');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(179, false, 'Justin Stone');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(180, false, 'Eugene Moore');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(181, false, 'Harry Barnes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(182, false, 'William Sanchez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(183, false, 'Edward Kelly');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(184, false, 'Laura Hamilton');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(185, false, 'Scott Romero');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(186, false, 'Kathryn Ortiz');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(187, false, 'Howard Hunter');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(188, false, 'Denise Young');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(189, false, 'Scott Little');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(190, false, 'Louis Mills');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(191, false, 'Denise Meyer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(192, false, 'Christina Parker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(193, false, 'Phillip Hamilton');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(194, false, 'Walter Robertson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(195, false, 'Lori Stephens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(196, false, 'Jeremy Bishop');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(197, false, 'Emily Tucker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(198, false, 'Samuel Coleman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(199, false, 'Cheryl Medina');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(200, false, 'Carol Cunningham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(201, false, 'Doris Burton');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(202, false, 'Craig Spencer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(203, false, 'Bobby Perry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(204, false, 'Edward Harper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(205, false, 'Laura Oliver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(206, false, 'Harold Crawford');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(207, false, 'Kathryn Matthews');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(208, false, 'Jean Grant');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(209, false, 'Nancy Walker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(210, false, 'Sarah Payne');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(211, false, 'Sara Simpson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(212, false, 'Andrew Owens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(213, false, 'Cheryl Boyd');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(214, false, 'Russell Phillips');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(215, false, 'Martha Hunt');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(216, false, 'Victor Willis');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(217, false, 'Benjamin Long');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(218, false, 'Robin Medina');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(219, false, 'Paula Ryan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(220, false, 'Amanda Walker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(221, false, 'Samuel Morrison');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(222, false, 'Sandra Sullivan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(223, false, 'Diana Reynolds');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(224, false, 'Barbara Palmer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(225, false, 'Jacqueline Boyd');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(226, false, 'Maria Nichols');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(227, false, 'Michelle Simmons');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(228, false, 'Beverly Little');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(229, false, 'Christine Pierce');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(230, false, 'Dorothy Barnes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(231, false, 'Paula Fernandez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(232, false, 'Terry Fields');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(233, false, 'Billy Franklin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(234, false, 'Denise Freeman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(235, false, 'Dennis Alexander');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(236, false, 'Annie Kim');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(237, false, 'Sandra Hill');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(238, false, 'Jane Collins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(239, false, 'Steve Crawford');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(240, false, 'Raymond Ellis');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(241, false, 'Kelly Rose');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(242, false, 'Judith Rose');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(243, false, 'Frank Griffin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(244, false, 'Michelle West');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(245, false, 'Clarence Smith');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(246, false, 'Mildred Hall');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(247, false, 'Ryan Chapman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(248, false, 'Virginia Rivera');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(249, false, 'Fred Garcia');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(250, false, 'Andrea Weaver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(251, false, 'Jacqueline Weaver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(252, false, 'Daniel Oliver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(253, false, 'Tina Dixon');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(254, false, 'Annie Powell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(255, false, 'Howard Hansen');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(256, false, 'Jane Thompson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(257, false, 'Alan Williams');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(258, false, 'Clarence Butler');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(259, false, 'Jean Fernandez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(260, false, 'Kevin Perez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(261, false, 'Earl Tucker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(262, false, 'Matthew Richards');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(263, false, 'Kathleen Gonzalez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(264, false, 'Ruth Williamson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(265, false, 'Andrea Fox');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(266, false, 'Christine Martinez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(267, false, 'Christina Carpenter');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(268, false, 'Jack Dunn');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(269, false, 'Kevin Hayes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(270, false, 'Matthew Roberts');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(271, false, 'Janice Rogers');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(272, false, 'Judy Oliver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(273, false, 'Amanda Howell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(274, false, 'Philip Henry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(275, false, 'Phillip Richards');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(276, false, 'Steve Hill');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(277, false, 'Roger Hunt');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(278, false, 'Shirley Simpson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(279, false, 'Brian Perkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(280, false, 'Bruce Weaver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(281, false, 'Christopher Scott');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(282, false, 'Rose Perry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(283, false, 'Earl Bradley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(284, false, 'Barbara Alexander');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(285, false, 'Julie Murphy');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(286, false, 'Gerald Moore');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(287, false, 'Clarence Myers');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(288, false, 'Theresa West');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(289, false, 'Brenda Mendoza');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(290, false, 'Ashley Fields');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(291, false, 'Joan Phillips');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(292, false, 'Billy Cook');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(293, false, 'Jacqueline Ortiz');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(294, false, 'Ryan Henry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(295, false, 'Sharon Wells');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(296, false, 'Patricia Watson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(297, false, 'Jessica Alvarez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(298, false, 'Steven Griffin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(299, false, 'Judy Greene');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(300, false, 'Roy Hunt');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(301, false, 'Craig Little');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(302, false, 'Anna Long');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(303, false, 'Linda Tucker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(304, false, 'Juan Coleman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(305, false, 'Tina Sullivan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(306, false, 'Marie Owens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(307, false, 'Jonathan Stanley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(308, false, 'Carl Palmer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(309, false, 'Keith Ford');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(310, false, 'Juan Fox');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(311, false, 'Scott Wallace');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(312, false, 'Jessica Smith');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(313, false, 'Julia Porter');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(314, false, 'Irene Green');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(315, false, 'Joan Ramos');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(316, false, 'Larry Little');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(317, false, 'Nicholas Graham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(318, false, 'Debra Palmer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(319, false, 'Thomas Dean');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(320, false, 'Lawrence Martinez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(321, false, 'Wayne Watkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(322, false, 'Christopher Kennedy');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(323, false, 'Joyce Williams');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(324, false, 'Bonnie Watkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(325, false, 'Martin Watkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(326, false, 'Julie Welch');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(327, false, 'Catherine Hamilton');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(328, false, 'James Ross');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(329, false, 'Stephen Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(330, false, 'Paul Bell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(331, false, 'Randy Watkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(332, false, 'Gerald Peters');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(333, false, 'Robin Torres');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(334, false, 'Donald King');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(335, false, 'Lori Smith');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(336, false, 'Craig Coleman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(337, false, 'Charles Harrison');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(338, false, 'Dennis Morales');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(339, false, 'Mark Johnson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(340, false, 'Nicole Spencer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(341, false, 'Bobby Burton');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(342, false, 'Craig Wilson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(343, false, 'Nicole Perez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(344, false, 'Kathleen Gilbert');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(345, false, 'Billy Price');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(346, false, 'Lawrence Morgan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(347, false, 'Scott Reyes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(348, false, 'Albert Adams');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(349, false, 'Judy Perry');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(350, false, 'Pamela Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(351, false, 'Russell Murphy');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(352, false, 'Joyce Mcdonald');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(353, false, 'Carlos Warren');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(354, false, 'Aaron Castillo');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(355, false, 'Catherine Lawson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(356, false, 'Emily Watson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(357, false, 'Jonathan Carter');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(358, false, 'Charles Bryant');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(359, false, 'Paula Kim');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(360, false, 'Howard Griffin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(361, false, 'Judy Jordan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(362, false, 'Katherine James');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(363, false, 'Brandon Matthews');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(364, false, 'Judith Williams');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(365, false, 'Ann Elliott');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(366, false, 'Sara Stevens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(367, false, 'Ernest Castillo');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(368, false, 'Paula Welch');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(369, false, 'Norma Garza');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(370, false, 'Peter Cox');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(371, false, 'Jesse Austin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(372, false, 'Willie Burton');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(373, false, 'Virginia Owens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(374, false, 'Earl Ward');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(375, false, 'Cynthia Hanson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(376, false, 'Donald Peters');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(377, false, 'Steve Ford');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(378, false, 'Christina Scott');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(379, false, 'James Pierce');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(380, false, 'Louise Williamson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(381, false, 'Kathleen Mills');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(382, false, 'Amy Richards');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(383, false, 'Lori Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(384, false, 'Louise Mendoza');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(385, false, 'Rebecca Owens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(386, false, 'Carlos Dunn');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(387, false, 'Thomas Kennedy');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(388, false, 'Betty Jenkins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(389, false, 'Stephanie Ward');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(390, false, 'John Mills');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(391, false, 'Albert Ramirez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(392, false, 'Jeffrey Robinson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(393, false, 'Martha Campbell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(394, false, 'Christine Torres');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(395, false, 'Antonio Weaver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(396, false, 'Harry Olson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(397, false, 'Anthony Peters');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(398, false, 'Brian Johnson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(399, false, 'Alice Morrison');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(400, false, 'Laura Gilbert');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(401, false, 'John Holmes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(402, false, 'Earl Peters');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(403, false, 'Johnny Johnson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(404, false, 'Ralph Jacobs');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(405, false, 'Cheryl Hunt');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(406, false, 'Diana Gray');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(407, false, 'Sean Romero');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(408, false, 'Betty White');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(409, false, 'Chris Elliott');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(410, false, 'Sean Cunningham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(411, false, 'Richard Myers');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(412, false, 'Louis Hansen');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(413, false, 'Karen Rodriguez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(414, false, 'Pamela Martin');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(415, false, 'Eric Lopez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(416, false, 'Bobby Holmes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(417, false, 'Ronald Graham');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(418, false, 'Kenneth White');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(419, false, 'Richard Rodriguez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(420, false, 'Joshua Wheeler');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(421, false, 'Jean Stephens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(422, false, 'Russell Mason');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(423, false, 'Ruth Ramirez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(424, false, 'Patrick Bryant');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(425, false, 'Roy Hill');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(426, false, 'Barbara Anderson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(427, false, 'Ruth Garrett');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(428, false, 'Diane Ward');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(429, false, 'Steve Garcia');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(430, false, 'Cheryl Thomas');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(431, false, 'Edward Palmer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(432, false, 'Mark Hanson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(433, false, 'William Coleman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(434, false, 'Ann Palmer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(435, false, 'Elizabeth Johnson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(436, false, 'Deborah Rivera');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(437, false, 'Judith Sanders');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(438, false, 'Peter Lynch');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(439, false, 'Mary Turner');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(440, false, 'Betty Morrison');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(441, false, 'Amanda Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(442, false, 'Rebecca Roberts');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(443, false, 'Randy Palmer');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(444, false, 'Diane Thompson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(445, false, 'Catherine Morgan');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(446, false, 'Marie Bryant');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(447, false, 'Sarah Fisher');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(448, false, 'Clarence Diaz');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(449, false, 'Kathy Gibson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(450, false, 'Martin Scott');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(451, false, 'Andrew Cooper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(452, false, 'Deborah Hernandez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(453, false, 'Kimberly Oliver');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(454, false, 'Phillip Snyder');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(455, false, 'Jean Clark');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(456, false, 'Phyllis Day');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(457, false, 'Sarah Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(458, false, 'Arthur Crawford');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(459, false, 'Scott Rogers');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(460, false, 'Karen Wheeler');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(461, false, 'Alice Cook');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(462, false, 'Frances Gordon');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(463, false, 'Adam Ford');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(464, false, 'Roy Cooper');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(465, false, 'Virginia Gardner');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(466, false, 'Louis Owens');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(467, false, 'Matthew Wood');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(468, false, 'Jerry Arnold');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(469, false, 'Phillip Rogers');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(470, false, 'Philip Washington');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(471, false, 'Pamela Snyder');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(472, false, 'Tina Moore');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(473, false, 'Todd Taylor');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(474, false, 'Jeremy Medina');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(475, false, 'Lillian Mitchell');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(476, false, 'Heather Stanley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(477, false, 'Jonathan Freeman');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(478, false, 'Diana Wright');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(479, false, 'Amanda Day');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(480, false, 'Julia Gordon');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(481, false, 'Cheryl Banks');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(482, false, 'Sara Reyes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(483, false, 'Kathryn Collins');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(484, false, 'Gary Stone');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(485, false, 'Gary Rogers');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(486, false, 'Kelly Johnson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(487, false, 'Harold Payne');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(488, false, 'James Day');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(489, false, 'Arthur Greene');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(490, false, 'James Chavez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(491, false, 'Ruth Harvey');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(492, false, 'Bobby Sims');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(493, false, 'Raymond Barnes');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(494, false, 'Lois Sanchez');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(495, false, 'Lisa Gordon');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(496, false, 'Billy Riley');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(497, false, 'Edward Olson');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(498, false, 'Thomas Harrison');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(499, false, 'Bruce Walker');
INSERT INTO opm.claim_officer(id, deleted, name) VALUES(500, false, 'Juan Evans');

INSERT INTO opm.pay_type(id, deleted, name) VALUES (1, false, 'UNKNOWN');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (2, false, 'ANNUAL SALARY');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (3, false, 'HOURLY RATE');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (4, false, 'EARNINGS');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (5, false, 'REFUND');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (6, false, 'Daily Rate');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (7, false, 'MONTHLY SALARY');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (8, false, 'Biweekly Rate');
INSERT INTO opm.pay_type(id, deleted, name) VALUES (9, false, 'Deduction Amount');

INSERT INTO opm.appointment_type(id, deleted, name) VALUES(1, false, 'DEPOSIT');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(2, false, 'CAREER');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(3, false, 'Career XXX');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(4, false, 'TEMPORARY');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(5, false, 'NTE');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(6, false, 'TERM');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(7, false, 'Excepted');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(8, false, 'INTERMITTENT');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(9, false, 'Taper');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(10, false, 'Indefinite');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(11, false, 'Unknown-deduction');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(12, false, 'Unknown-nondeduction');
INSERT INTO opm.appointment_type(id, deleted, name) VALUES(13, false, 'Not applicable');

INSERT INTO opm.transfer_type(id, deleted, name) VALUES(1, false, 'Refund Payment');
INSERT INTO opm.transfer_type(id, deleted, name) VALUES(2, false, 'Direct Pay Life Insurance');
INSERT INTO opm.transfer_type(id, deleted, name) VALUES(3, false, 'Voluntary Contributions');
INSERT INTO opm.transfer_type(id, deleted, name) VALUES(4, false, 'Debit Voucher');
INSERT INTO opm.transfer_type(id, deleted, name) VALUES(5, false, 'Annuity');

INSERT INTO opm.period_type(id, deleted, name) VALUES (1, false, 'DEPOSIT');
INSERT INTO opm.period_type(id, deleted, name) VALUES (2, false, 'REDEPOSIT');
INSERT INTO opm.period_type(id, deleted, name) VALUES (3, false, 'Military');
INSERT INTO opm.period_type(id, deleted, name) VALUES (4, false, 'LWOP');
INSERT INTO opm.period_type(id, deleted, name) VALUES (5, false, 'NO EARNINGS');
INSERT INTO opm.period_type(id, deleted, name) VALUES (6, false, 'Deduction Service');
INSERT INTO opm.period_type(id, deleted, name) VALUES (7, false, 'Unpaid Redeposit');
INSERT INTO opm.period_type(id, deleted, name) VALUES (8, false, 'Pre 10-82 Redeposit');
INSERT INTO opm.period_type(id, deleted, name) VALUES (9, false, 'Post 10-82 Redeposit');
INSERT INTO opm.period_type(id, deleted, name) VALUES (10, false, 'Post 03-91 Redeposit');
INSERT INTO opm.period_type(id, deleted, name) VALUES (11, false, 'Pre 03-91 Redeposit');

INSERT INTO opm.user_status(id, deleted, name) VALUES(1, false, 'Active User');
INSERT INTO opm.user_status(id, deleted, name) VALUES(2, false, 'Suspended User');


INSERT INTO opm.retirement_type(id, deleted, name) VALUES(1, false, 'FERS');
INSERT INTO opm.retirement_type(id, deleted, name) VALUES(2, false, 'CSRS');

INSERT INTO opm.form_type(id, deleted, name) VALUES(1, false, '3108(FERS)');
INSERT INTO opm.form_type(id, deleted, name) VALUES(2, false, '2803(CSRS)');

INSERT INTO opm.account_status(id, deleted, name) VALUES(1, false, 'Active');
INSERT INTO opm.account_status(id, deleted, name) VALUES(2, false, 'Suspended');
INSERT INTO opm.account_status(id, deleted, name) VALUES(3, false, 'Closed');

INSERT INTO opm.suffix(id, deleted, name) VALUES(1, false,'I');
INSERT INTO opm.suffix(id, deleted, name) VALUES(2, false,'II');
INSERT INTO opm.suffix(id, deleted, name) VALUES(3, false,'III');
INSERT INTO opm.suffix(id, deleted, name) VALUES(4, false,'JR');
INSERT INTO opm.suffix(id, deleted, name) VALUES(5, false,'SR');

INSERT INTO opm.state(id, deleted, name) values(1, false, 'Not Applicable');
INSERT INTO opm.state(id, deleted, name) values(2, false, 'AL');
INSERT INTO opm.state(id, deleted, name) values(3, false, 'AK');
INSERT INTO opm.state(id, deleted, name) values(4, false, 'AZ');
INSERT INTO opm.state(id, deleted, name) values(5, false, 'AR');
INSERT INTO opm.state(id, deleted, name) values(6, false, 'CA');
INSERT INTO opm.state(id, deleted, name) values(7, false, 'CO');
INSERT INTO opm.state(id, deleted, name) values(8, false, 'CT');
INSERT INTO opm.state(id, deleted, name) values(9, false, 'DE');
INSERT INTO opm.state(id, deleted, name) values(10, false, 'FL');
INSERT INTO opm.state(id, deleted, name) values(11, false, 'GA');
INSERT INTO opm.state(id, deleted, name) values(12, false, 'HI');
INSERT INTO opm.state(id, deleted, name) values(13, false, 'ID');
INSERT INTO opm.state(id, deleted, name) values(14, false, 'IL');
INSERT INTO opm.state(id, deleted, name) values(15, false, 'IN');
INSERT INTO opm.state(id, deleted, name) values(16, false, 'IA');
INSERT INTO opm.state(id, deleted, name) values(17, false, 'KS');
INSERT INTO opm.state(id, deleted, name) values(18, false, 'KY');
INSERT INTO opm.state(id, deleted, name) values(19, false, 'LA');
INSERT INTO opm.state(id, deleted, name) values(20, false, 'ME');
INSERT INTO opm.state(id, deleted, name) values(21, false, 'MD');
INSERT INTO opm.state(id, deleted, name) values(22, false, 'MA');
INSERT INTO opm.state(id, deleted, name) values(23, false, 'MI');
INSERT INTO opm.state(id, deleted, name) values(24, false, 'MN');
INSERT INTO opm.state(id, deleted, name) values(25, false, 'MS');
INSERT INTO opm.state(id, deleted, name) values(26, false, 'MO');
INSERT INTO opm.state(id, deleted, name) values(27, false, 'MT');
INSERT INTO opm.state(id, deleted, name) values(28, false, 'NE');
INSERT INTO opm.state(id, deleted, name) values(29, false, 'NV');
INSERT INTO opm.state(id, deleted, name) values(30, false, 'NH');
INSERT INTO opm.state(id, deleted, name) values(31, false, 'NJ');
INSERT INTO opm.state(id, deleted, name) values(32, false, 'NM');
INSERT INTO opm.state(id, deleted, name) values(33, false, 'NY');
INSERT INTO opm.state(id, deleted, name) values(34, false, 'NC');
INSERT INTO opm.state(id, deleted, name) values(35, false, 'ND');
INSERT INTO opm.state(id, deleted, name) values(36, false, 'OH');
INSERT INTO opm.state(id, deleted, name) values(37, false, 'OK');
INSERT INTO opm.state(id, deleted, name) values(38, false, 'OR');
INSERT INTO opm.state(id, deleted, name) values(39, false, 'PA');
INSERT INTO opm.state(id, deleted, name) values(40, false, 'RI');
INSERT INTO opm.state(id, deleted, name) values(41, false, 'SC');
INSERT INTO opm.state(id, deleted, name) values(42, false, 'SD');
INSERT INTO opm.state(id, deleted, name) values(43, false, 'TN');
INSERT INTO opm.state(id, deleted, name) values(44, false, 'TX');
INSERT INTO opm.state(id, deleted, name) values(45, false, 'UT');
INSERT INTO opm.state(id, deleted, name) values(46, false, 'VT');
INSERT INTO opm.state(id, deleted, name) values(47, false, 'VA');
INSERT INTO opm.state(id, deleted, name) values(48, false, 'WA');
INSERT INTO opm.state(id, deleted, name) values(49, false, 'WV');
INSERT INTO opm.state(id, deleted, name) values(50, false, 'WI');
INSERT INTO opm.state(id, deleted, name) values(51, false, 'WY');

INSERT INTO opm.country(id, deleted, name) VALUES (1, false,'Afghanistan');
INSERT INTO opm.country(id, deleted, name) VALUES (2, false,'Albania');
INSERT INTO opm.country(id, deleted, name) VALUES (3, false,'Algeria');
INSERT INTO opm.country(id, deleted, name) VALUES (4, false,'Andorra');
INSERT INTO opm.country(id, deleted, name) VALUES (5, false,'Angola');
INSERT INTO opm.country(id, deleted, name) VALUES (6, false,'Antigua and Barbuda');
INSERT INTO opm.country(id, deleted, name) VALUES (7, false,'Argentina');
INSERT INTO opm.country(id, deleted, name) VALUES (8, false,'Armenia');
INSERT INTO opm.country(id, deleted, name) VALUES (9, false,'Aruba');
INSERT INTO opm.country(id, deleted, name) VALUES (10, false,'Australia');
INSERT INTO opm.country(id, deleted, name) VALUES (11, false,'Austria');
INSERT INTO opm.country(id, deleted, name) VALUES (12, false,'Azerbaijan');
INSERT INTO opm.country(id, deleted, name) VALUES (13, false,'Bahamas, The');
INSERT INTO opm.country(id, deleted, name) VALUES (14, false,'Bahrain');
INSERT INTO opm.country(id, deleted, name) VALUES (15, false,'Bangladesh');
INSERT INTO opm.country(id, deleted, name) VALUES (16, false,'Barbados');
INSERT INTO opm.country(id, deleted, name) VALUES (17, false,'Belarus');
INSERT INTO opm.country(id, deleted, name) VALUES (18, false,'Belgium');
INSERT INTO opm.country(id, deleted, name) VALUES (19, false,'Belize');
INSERT INTO opm.country(id, deleted, name) VALUES (20, false,'Benin');
INSERT INTO opm.country(id, deleted, name) VALUES (21, false,'Bhutan');
INSERT INTO opm.country(id, deleted, name) VALUES (22, false,'Bolivia');
INSERT INTO opm.country(id, deleted, name) VALUES (23, false,'Bosnia and Herzegovina');
INSERT INTO opm.country(id, deleted, name) VALUES (24, false,'Botswana');
INSERT INTO opm.country(id, deleted, name) VALUES (25, false,'Brazil');
INSERT INTO opm.country(id, deleted, name) VALUES (26, false,'Brunei ');
INSERT INTO opm.country(id, deleted, name) VALUES (27, false,'Bulgaria');
INSERT INTO opm.country(id, deleted, name) VALUES (28, false,'Burkina Faso');
INSERT INTO opm.country(id, deleted, name) VALUES (29, false,'Burma');
INSERT INTO opm.country(id, deleted, name) VALUES (30, false,'Burundi');
INSERT INTO opm.country(id, deleted, name) VALUES (31, false,'Cambodia');
INSERT INTO opm.country(id, deleted, name) VALUES (32, false,'Cameroon');
INSERT INTO opm.country(id, deleted, name) VALUES (33, false,'Canada');
INSERT INTO opm.country(id, deleted, name) VALUES (34, false,'Cape Verde');
INSERT INTO opm.country(id, deleted, name) VALUES (35, false,'Central African Republic');
INSERT INTO opm.country(id, deleted, name) VALUES (36, false,'Chad');
INSERT INTO opm.country(id, deleted, name) VALUES (37, false,'Chile');
INSERT INTO opm.country(id, deleted, name) VALUES (38, false,'China');
INSERT INTO opm.country(id, deleted, name) VALUES (39, false,'Colombia');
INSERT INTO opm.country(id, deleted, name) VALUES (40, false,'Comoros');
INSERT INTO opm.country(id, deleted, name) VALUES (41, false,'Congo, Democratic Republic of the');
INSERT INTO opm.country(id, deleted, name) VALUES (42, false,'Costa Rica');
INSERT INTO opm.country(id, deleted, name) VALUES (43, false,'Cote d''Ivoire');
INSERT INTO opm.country(id, deleted, name) VALUES (44, false,'Croatia');
INSERT INTO opm.country(id, deleted, name) VALUES (45, false,'Cuba');
INSERT INTO opm.country(id, deleted, name) VALUES (46, false,'Curacao');
INSERT INTO opm.country(id, deleted, name) VALUES (47, false,'Cyprus');
INSERT INTO opm.country(id, deleted, name) VALUES (48, false,'Czech Republic');
INSERT INTO opm.country(id, deleted, name) VALUES (49, false,'Denmark');
INSERT INTO opm.country(id, deleted, name) VALUES (50, false,'Djibouti');
INSERT INTO opm.country(id, deleted, name) VALUES (51, false,'Dominica');
INSERT INTO opm.country(id, deleted, name) VALUES (52, false,'Dominican Republic');
INSERT INTO opm.country(id, deleted, name) VALUES (53, false,'East Timor (see Timor-Leste)');
INSERT INTO opm.country(id, deleted, name) VALUES (54, false,'Ecuador');
INSERT INTO opm.country(id, deleted, name) VALUES (55, false,'Egypt');
INSERT INTO opm.country(id, deleted, name) VALUES (56, false,'El Salvador');
INSERT INTO opm.country(id, deleted, name) VALUES (57, false,'Equatorial Guinea');
INSERT INTO opm.country(id, deleted, name) VALUES (58, false,'Eritrea');
INSERT INTO opm.country(id, deleted, name) VALUES (59, false,'Estonia');
INSERT INTO opm.country(id, deleted, name) VALUES (60, false,'Ethiopia');
INSERT INTO opm.country(id, deleted, name) VALUES (61, false,'Fiji');
INSERT INTO opm.country(id, deleted, name) VALUES (62, false,'Finland');
INSERT INTO opm.country(id, deleted, name) VALUES (63, false,'France');
INSERT INTO opm.country(id, deleted, name) VALUES (64, false,'Gabon');
INSERT INTO opm.country(id, deleted, name) VALUES (65, false,'Gambia, The');
INSERT INTO opm.country(id, deleted, name) VALUES (66, false,'Georgia');
INSERT INTO opm.country(id, deleted, name) VALUES (67, false,'Germany');
INSERT INTO opm.country(id, deleted, name) VALUES (68, false,'Ghana');
INSERT INTO opm.country(id, deleted, name) VALUES (69, false,'Greece');
INSERT INTO opm.country(id, deleted, name) VALUES (70, false,'Grenada');
INSERT INTO opm.country(id, deleted, name) VALUES (71, false,'Guatemala');
INSERT INTO opm.country(id, deleted, name) VALUES (72, false,'Guinea');
INSERT INTO opm.country(id, deleted, name) VALUES (73, false,'Guinea-Bissau');
INSERT INTO opm.country(id, deleted, name) VALUES (74, false,'Guyana');
INSERT INTO opm.country(id, deleted, name) VALUES (75, false,'Haiti');
INSERT INTO opm.country(id, deleted, name) VALUES (76, false,'Holy See');
INSERT INTO opm.country(id, deleted, name) VALUES (77, false,'Honduras');
INSERT INTO opm.country(id, deleted, name) VALUES (78, false,'Hong Kong');
INSERT INTO opm.country(id, deleted, name) VALUES (79, false,'Hungary');
INSERT INTO opm.country(id, deleted, name) VALUES (80, false,'Iceland');
INSERT INTO opm.country(id, deleted, name) VALUES (81, false,'India');
INSERT INTO opm.country(id, deleted, name) VALUES (82, false,'Indonesia');
INSERT INTO opm.country(id, deleted, name) VALUES (83, false,'Iran');
INSERT INTO opm.country(id, deleted, name) VALUES (84, false,'Iraq');
INSERT INTO opm.country(id, deleted, name) VALUES (85, false,'Ireland');
INSERT INTO opm.country(id, deleted, name) VALUES (86, false,'Israel');
INSERT INTO opm.country(id, deleted, name) VALUES (87, false,'Italy');
INSERT INTO opm.country(id, deleted, name) VALUES (88, false,'Jamaica');
INSERT INTO opm.country(id, deleted, name) VALUES (89, false,'Japan');
INSERT INTO opm.country(id, deleted, name) VALUES (90, false,'Jordan');
INSERT INTO opm.country(id, deleted, name) VALUES (91, false,'Kazakhstan');
INSERT INTO opm.country(id, deleted, name) VALUES (92, false,'Kenya');
INSERT INTO opm.country(id, deleted, name) VALUES (93, false,'Kiribati');
INSERT INTO opm.country(id, deleted, name) VALUES (94, false,'Korea, North');
INSERT INTO opm.country(id, deleted, name) VALUES (95, false,'Korea, South');
INSERT INTO opm.country(id, deleted, name) VALUES (96, false,'Kosovo');
INSERT INTO opm.country(id, deleted, name) VALUES (97, false,'Kuwait');
INSERT INTO opm.country(id, deleted, name) VALUES (98, false,'Kyrgyzstan');
INSERT INTO opm.country(id, deleted, name) VALUES (99, false,'Laos');
INSERT INTO opm.country(id, deleted, name) VALUES (100, false,'Latvia');
INSERT INTO opm.country(id, deleted, name) VALUES (101, false,'Lebanon');
INSERT INTO opm.country(id, deleted, name) VALUES (102, false,'Lesotho');
INSERT INTO opm.country(id, deleted, name) VALUES (103, false,'Liberia');
INSERT INTO opm.country(id, deleted, name) VALUES (104, false,'Libya');
INSERT INTO opm.country(id, deleted, name) VALUES (105, false,'Liechtenstein');
INSERT INTO opm.country(id, deleted, name) VALUES (106, false,'Lithuania');
INSERT INTO opm.country(id, deleted, name) VALUES (107, false,'Luxembourg');
INSERT INTO opm.country(id, deleted, name) VALUES (108, false,'Macau');
INSERT INTO opm.country(id, deleted, name) VALUES (109, false,'Macedonia');
INSERT INTO opm.country(id, deleted, name) VALUES (110, false,'Madagascar');
INSERT INTO opm.country(id, deleted, name) VALUES (111, false,'Malawi');
INSERT INTO opm.country(id, deleted, name) VALUES (112, false,'Malaysia');
INSERT INTO opm.country(id, deleted, name) VALUES (113, false,'Maldives');
INSERT INTO opm.country(id, deleted, name) VALUES (114, false,'Mali');
INSERT INTO opm.country(id, deleted, name) VALUES (115, false,'Malta');
INSERT INTO opm.country(id, deleted, name) VALUES (116, false,'Marshall Islands');
INSERT INTO opm.country(id, deleted, name) VALUES (117, false,'Mauritania');
INSERT INTO opm.country(id, deleted, name) VALUES (118, false,'Mauritius');
INSERT INTO opm.country(id, deleted, name) VALUES (119, false,'Mexico');
INSERT INTO opm.country(id, deleted, name) VALUES (120, false,'Micronesia');
INSERT INTO opm.country(id, deleted, name) VALUES (121, false,'Moldova');
INSERT INTO opm.country(id, deleted, name) VALUES (122, false,'Monaco');
INSERT INTO opm.country(id, deleted, name) VALUES (123, false,'Mongolia');
INSERT INTO opm.country(id, deleted, name) VALUES (124, false,'Montenegro');
INSERT INTO opm.country(id, deleted, name) VALUES (125, false,'Morocco');
INSERT INTO opm.country(id, deleted, name) VALUES (126, false,'Mozambique');
INSERT INTO opm.country(id, deleted, name) VALUES (127, false,'Namibia');
INSERT INTO opm.country(id, deleted, name) VALUES (128, false,'Nauru');
INSERT INTO opm.country(id, deleted, name) VALUES (129, false,'Nepal');
INSERT INTO opm.country(id, deleted, name) VALUES (130, false,'Netherlands');
INSERT INTO opm.country(id, deleted, name) VALUES (131, false,'Netherlands Antilles');
INSERT INTO opm.country(id, deleted, name) VALUES (132, false,'New Zealand');
INSERT INTO opm.country(id, deleted, name) VALUES (133, false,'Nicaragua');
INSERT INTO opm.country(id, deleted, name) VALUES (134, false,'Niger');
INSERT INTO opm.country(id, deleted, name) VALUES (135, false,'Nigeria');
INSERT INTO opm.country(id, deleted, name) VALUES (136, false,'North Korea');
INSERT INTO opm.country(id, deleted, name) VALUES (137, false,'Norway');
INSERT INTO opm.country(id, deleted, name) VALUES (138, false,'Oman');
INSERT INTO opm.country(id, deleted, name) VALUES (139, false,'Pakistan');
INSERT INTO opm.country(id, deleted, name) VALUES (140, false,'Palau');
INSERT INTO opm.country(id, deleted, name) VALUES (141, false,'Palestinian Territories');
INSERT INTO opm.country(id, deleted, name) VALUES (142, false,'Panama');
INSERT INTO opm.country(id, deleted, name) VALUES (143, false,'Papua New Guinea');
INSERT INTO opm.country(id, deleted, name) VALUES (144, false,'Paraguay');
INSERT INTO opm.country(id, deleted, name) VALUES (145, false,'Peru');
INSERT INTO opm.country(id, deleted, name) VALUES (146, false,'Philippines');
INSERT INTO opm.country(id, deleted, name) VALUES (147, false,'Poland');
INSERT INTO opm.country(id, deleted, name) VALUES (148, false,'Portugal');
INSERT INTO opm.country(id, deleted, name) VALUES (149, false,'Qatar');
INSERT INTO opm.country(id, deleted, name) VALUES (150, false,'Romania');
INSERT INTO opm.country(id, deleted, name) VALUES (151, false,'Russia');
INSERT INTO opm.country(id, deleted, name) VALUES (152, false,'Rwanda');
INSERT INTO opm.country(id, deleted, name) VALUES (153, false,'Saint Kitts and Nevis');
INSERT INTO opm.country(id, deleted, name) VALUES (154, false,'Saint Lucia');
INSERT INTO opm.country(id, deleted, name) VALUES (155, false,'Saint Vincent and the Grenadines');
INSERT INTO opm.country(id, deleted, name) VALUES (156, false,'Samoa');
INSERT INTO opm.country(id, deleted, name) VALUES (157, false,'San Marino');
INSERT INTO opm.country(id, deleted, name) VALUES (158, false,'Sao Tome and Principe');
INSERT INTO opm.country(id, deleted, name) VALUES (159, false,'Saudi Arabia');
INSERT INTO opm.country(id, deleted, name) VALUES (160, false,'Senegal');
INSERT INTO opm.country(id, deleted, name) VALUES (161, false,'Serbia');
INSERT INTO opm.country(id, deleted, name) VALUES (162, false,'Seychelles');
INSERT INTO opm.country(id, deleted, name) VALUES (163, false,'Sierra Leone');
INSERT INTO opm.country(id, deleted, name) VALUES (164, false,'Singapore');
INSERT INTO opm.country(id, deleted, name) VALUES (165, false,'Sint Maarten');
INSERT INTO opm.country(id, deleted, name) VALUES (166, false,'Slovakia');
INSERT INTO opm.country(id, deleted, name) VALUES (167, false,'Slovenia');
INSERT INTO opm.country(id, deleted, name) VALUES (168, false,'Solomon Islands');
INSERT INTO opm.country(id, deleted, name) VALUES (169, false,'Somalia');
INSERT INTO opm.country(id, deleted, name) VALUES (170, false,'South Africa');
INSERT INTO opm.country(id, deleted, name) VALUES (171, false,'South Korea');
INSERT INTO opm.country(id, deleted, name) VALUES (172, false,'South Sudan');
INSERT INTO opm.country(id, deleted, name) VALUES (173, false,'Spain');
INSERT INTO opm.country(id, deleted, name) VALUES (174, false,'Sri Lanka');
INSERT INTO opm.country(id, deleted, name) VALUES (175, false,'Sudan');
INSERT INTO opm.country(id, deleted, name) VALUES (176, false,'Suriname');
INSERT INTO opm.country(id, deleted, name) VALUES (177, false,'Swaziland');
INSERT INTO opm.country(id, deleted, name) VALUES (178, false,'Sweden');
INSERT INTO opm.country(id, deleted, name) VALUES (179, false,'Switzerland');
INSERT INTO opm.country(id, deleted, name) VALUES (180, false,'Syria');
INSERT INTO opm.country(id, deleted, name) VALUES (181, false,'Taiwan');
INSERT INTO opm.country(id, deleted, name) VALUES (182, false,'Tajikistan');
INSERT INTO opm.country(id, deleted, name) VALUES (183, false,'Tanzania');
INSERT INTO opm.country(id, deleted, name) VALUES (184, false,'Thailand ');
INSERT INTO opm.country(id, deleted, name) VALUES (185, false,'Timor-Leste');
INSERT INTO opm.country(id, deleted, name) VALUES (186, false,'Togo');
INSERT INTO opm.country(id, deleted, name) VALUES (187, false,'Tonga');
INSERT INTO opm.country(id, deleted, name) VALUES (188, false,'Trinidad and Tobago');
INSERT INTO opm.country(id, deleted, name) VALUES (189, false,'Tunisia');
INSERT INTO opm.country(id, deleted, name) VALUES (190, false,'Turkey');
INSERT INTO opm.country(id, deleted, name) VALUES (191, false,'Turkmenistan');
INSERT INTO opm.country(id, deleted, name) VALUES (192, false,'Tuvalu');
INSERT INTO opm.country(id, deleted, name) VALUES (193, false,'Uganda');
INSERT INTO opm.country(id, deleted, name) VALUES (194, false,'Ukraine');
INSERT INTO opm.country(id, deleted, name) VALUES (195, false,'United Arab Emirates');
INSERT INTO opm.country(id, deleted, name) VALUES (196, false,'United Kingdom');
INSERT INTO opm.country(id, deleted, name) VALUES (197, false,'United States');
INSERT INTO opm.country(id, deleted, name) VALUES (198, false,'Uruguay');
INSERT INTO opm.country(id, deleted, name) VALUES (199, false,'Uzbekistan');
INSERT INTO opm.country(id, deleted, name) VALUES (200, false,'Vanuatu');
INSERT INTO opm.country(id, deleted, name) VALUES (201, false,'Venezuela');
INSERT INTO opm.country(id, deleted, name) VALUES (202, false,'Vietnam');
INSERT INTO opm.country(id, deleted, name) VALUES (203, false,'Yemen');
INSERT INTO opm.country(id, deleted, name) VALUES (204, false,'Zambia');
INSERT INTO opm.country(id, deleted, name) VALUES (205, false,'Zimbabwe');

INSERT INTO opm.payment_status(id, deleted, name) VALUES(1, false, 'Posted - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(2, false, 'Reversed - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(3, false, 'Reversed - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(4, false, 'Voluntary Contributions - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(5, false, 'Voluntary Contributions - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(6, false, 'Direct Pay Life - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(7, false, 'Direct Pay Life - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(8, false, 'Suspense Refund Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(9, false, 'Suspense Refund Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(10, false, 'Annuity - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(11, false, 'Annuity - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(12, false, 'Debit Voucher - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(13, false, 'Debit Voucher - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(14, false, 'Health Benefits - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(15, false, 'Health Benefits - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(16, false, 'Adjustment - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(17, false, 'Adjustment - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(18, false, 'Write-Off - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(19, false, 'Write-Off - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(20, false, 'Credit Balance Refund - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(21, false, 'Credit Balance Refund - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(22, false, 'Batch Auto Refund Cancelled - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(23, false, 'Batch Auto Refund Cancelled - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(24, false, 'Manual Adjustment Cancelled - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(25, false, 'Manual Adjustment Cancelled - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(26, false, 'Batch Auto Refund - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(27, false, 'Batch Auto Refund - Pending');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(28, false, 'Unresolved');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(29, false, 'Suspended');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(30, false, 'Posted - Pending Approval');
INSERT INTO opm.payment_status(id, deleted, name) VALUES(31, false, 'Lockbox Bank error');

INSERT INTO opm.role (id, deleted, name, description) VALUES (1, false, 'Admin', 'Administrator');
INSERT INTO opm.role (id, deleted, name, description) VALUES (2, false, 'FinTech', 'FinTech');
INSERT INTO opm.role (id, deleted, name, description) VALUES (3, false, 'Faces', 'FACES User');
INSERT INTO opm.role (id, deleted, name, description) VALUES (4, false, 'supervisor', 'Supervisor');
INSERT INTO opm.role (id, deleted, name, description) VALUES (5, false, 'Customer Service Specialist', 'Customer Service Specialist');
INSERT INTO opm.role (id, deleted, name, description) VALUES (6, false, 'FACES User', 'FACES User');
INSERT INTO opm.role (id, deleted, name, description) VALUES (7, false, 'Financial Supervisor', 'Financial Supervisor');
INSERT INTO opm.role (id, deleted, name, description) VALUES (8, false, 'Financial Technician', 'Financial Technician');
INSERT INTO opm.role (id, deleted, name, description) VALUES (9, false, 'Information Technician', 'Information Technician');
INSERT INTO opm.role (id, deleted, name, description) VALUES (10, false, 'New User', 'New User');
INSERT INTO opm.role (id, deleted, name, description) VALUES (11, false, 'Receivables Supervisor', 'Receivables Supervisor');
INSERT INTO opm.role (id, deleted, name, description) VALUES (12, false, 'Receivables Technician', 'Receivables Technician');
INSERT INTO opm.role (id, deleted, name, description) VALUES (13, false, 'Refunds Data Entry', 'Refunds Data Entry');
INSERT INTO opm.role (id, deleted, name, description) VALUES (14, false, 'Refunds Specialist', 'Refunds Specialist');
INSERT INTO opm.role (id, deleted, name, description) VALUES (15, false, 'Refunds Supervisor', 'Refunds Supervisor');
INSERT INTO opm.role (id, deleted, name, description) VALUES (16, false, 'RIO  User', 'RIO  User');
INSERT INTO opm.role (id, deleted, name, description) VALUES (17, false, 'Batch Processing', 'Batch Processing');

INSERT INTO opm.application_designation(id, deleted, name) VALUES(1, false, 'Default User Order');
INSERT INTO opm.application_designation(id, deleted, name) VALUES(2, false, 'Pre Deposit');
INSERT INTO opm.application_designation(id, deleted, name) VALUES(3, false, 'Post Deposit');
INSERT INTO opm.application_designation(id, deleted, name) VALUES(4, false, 'Pre Redeposit');
INSERT INTO opm.application_designation(id, deleted, name) VALUES(5, false, 'Post Redeposit');
INSERT INTO opm.application_designation(id, deleted, name) VALUES(6, false, 'FERS');

INSERT INTO opm.app_user (id, deleted, username, default_tab, network_id, role_id, first_name, last_name, email, telephone, user_status_id, default_tab_account_id) VALUES (1, false, 'user1', 'VIEW_ACCOUNT', 'networkId1', 1, 'Jack', 'Hughes', 'Email1@topcoder.com', '212-999-0983', 1, 1);
INSERT INTO opm.app_user (id, deleted, username, default_tab, network_id, role_id, first_name, last_name, email, telephone, user_status_id, default_tab_account_id) VALUES (2, false, 'user2', 'VIEW_ACCOUNT', 'networkId2', 2, 'Mark', 'Zuckerberg', 'email2@topcoder.com', '212-999-0982', 1, 1);
INSERT INTO opm.app_user (id, deleted, username, default_tab, network_id, role_id, first_name, last_name, email, telephone, user_status_id, default_tab_account_id) VALUES (3, false, 'user3', 'VIEW_ACCOUNT', 'networkId3', 4, 'Posh', 'Gutenberg', 'posh@topcoder.com', '212-999-0982', 1, 1);
INSERT INTO opm.app_user (id, deleted, username, default_tab, network_id, role_id, first_name, last_name, email, telephone, user_status_id, default_tab_account_id) VALUES (4, false, 'user4', 'VIEW_ACCOUNT', 'networkId4', 4, 'Mesh', 'Winchester', 'mesh@topcoder.com', '212-999-0982', 1, 1);
INSERT INTO opm.app_user (id, deleted, username, default_tab, network_id, role_id, first_name, last_name, email, telephone, user_status_id, default_tab_account_id) VALUES (5, false, 'user5', 'VIEW_ACCOUNT', 'networkId5', 3, 'Bannie', 'Lai', 'email3@topcoder.com', '212-999-0982', 1, 1);
INSERT INTO opm.app_user (id, deleted, username, default_tab, network_id, role_id, first_name, last_name, email, telephone, user_status_id, default_tab_account_id) VALUES (6, false, 'ScrdAdmin@OPM.EC2.INTERNAL', 'VIEW_ACCOUNT', 'networkId5', 1, 'Windows', 'User', 'email3@topcoder.com', '212-999-0982', 1, 1);
INSERT INTO opm.app_user (id, deleted, username, default_tab, network_id, role_id, first_name, last_name, email, telephone, user_status_id, default_tab_account_id) VALUES (7, false, 'BatchUser', 'VIEW_ACCOUNT', 'networkId5', 17, 'Batch', 'User', 'email3@topcoder.com', '212-999-0982', 1, 1);

INSERT INTO opm.user_permission (id, deleted, username, action) VALUES (1, false, 'user1', 'link');
INSERT INTO opm.user_permission (id, deleted, username, action) VALUES (2, false, 'user1', 'button');
INSERT INTO opm.user_permission (id, deleted, username, action) VALUES (3, false, 'user1', 'table');
INSERT INTO opm.user_permission (id, deleted, username, action) VALUES (4, false, 'user1', 'control');

INSERT INTO opm.error (id, deleted, date, details) VALUES (1, false, CURRENT_TIMESTAMP, 'You have 2 records in <br/><a href="workQueue/view">Work Queue.</a>');
INSERT INTO opm.error (id, deleted, date, details) VALUES (2, false, CURRENT_TIMESTAMP - INTERVAL '16 days', 'Error before 15 days');

INSERT INTO opm.info (id, deleted, date, details) VALUES (1, false, CURRENT_TIMESTAMP, 'You have 1 record in <br/><a href="workQueue/view">Work Queue.</a>');
INSERT INTO opm.info (id, deleted, date, details) VALUES (2, false, CURRENT_TIMESTAMP, 'You have 2 records in <br/><a href="workQueue/view">Work Queue.</a>');
INSERT INTO opm.info (id, deleted, date, details) VALUES (3, false, CURRENT_TIMESTAMP - INTERVAL '16 days', 'Info before 15 days');

INSERT INTO opm.notification (id, deleted, date, details, sender, read, recipient) VALUES (1, false, CURRENT_TIMESTAMP, 'I reviewed the Account for John Doe and found an error in Billing Summary. Please fix. <a href="account/2002/detail">Click here to view the account</a>.', 'John Smith<br>(Supervisor)', false, 'user1');
INSERT INTO opm.notification (id, deleted, date, details, sender, read, recipient) VALUES (2, false, CURRENT_TIMESTAMP, '- You have 1 Record in <a href="workQueue/view">Work Queue.</a><br/>- You have 7 <a href="suspension/view">Payments in Suspense</a>.', 'System', false, 'user1');
INSERT INTO opm.notification (id, deleted, date, details, sender, read, recipient) VALUES (3, false, CURRENT_TIMESTAMP - INTERVAL '16 days', 'Notification before 15 days', 'System', false, 'user1');

INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (1, false, 'Admin', 'VIEW_ACCOUNT');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (2, false, 'Admin', 'CREATE_NEW_ACCOUNT');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (3, false, 'Admin', 'WORK_QUEUE');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (4, false, 'Admin', 'REPORTS');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (5, false, 'Admin', 'SUSPENSE');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (6, false, 'Admin', 'APPROVAL');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (7, false, 'Admin', 'PAYMENTS');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (8, false, 'Admin', 'TOOLS');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (9, false, 'Admin', 'ADMIN');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (10, false, 'Admin', 'NOTIFICATION_LOG');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (11, false, 'Admin', 'HELP');

INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (13, false, 'Admin', 'GET /lookup');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (14, false, 'Admin', 'GET /common');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (15, false, 'Admin', 'POST /common');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (16, false, 'Admin', 'GET /account');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (116, false, 'Admin', 'GET /letter');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (117, false, 'Admin', 'PUT /letter');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (118, false, 'Admin', 'POST /letter');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (119, false, 'Admin', 'DELETE /letter');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (120, false, 'Admin', 'GET /reference');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (121, false, 'Admin', 'PUT /reference');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (122, false, 'Admin', 'POST /reference');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (123, false, 'Admin', 'DELETE /reference');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (17, false, 'Admin', 'POST /account');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (18, false, 'Admin', 'PUT /account');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (19, false, 'Admin', 'DELETE /account');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (20, false, 'Admin', 'GET /workQueue');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (21, false, 'Admin', 'POST /workQueue');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (22, false, 'Admin', 'GET /report');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (222, false, 'Admin', 'POST /report');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (23, false, 'Admin', 'GET /suspension');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (24, false, 'Admin', 'POST /suspension');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (25, false, 'Admin', 'GET /approval');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (26, false, 'Admin', 'PUT /approval');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (27, false, 'Admin', 'POST /approval');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (28, false, 'Admin', 'GET /payment');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (29, false, 'Admin', 'PUT /payment');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (30, false, 'Admin', 'POST /payment');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (31, false, 'Admin', 'DELETE /payment');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (32, false, 'Admin', 'GET /tools');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (33, false, 'Admin', 'POST /tools');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (34, false, 'Admin', 'GET /admin');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (35, false, 'Admin', 'PUT /admin');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (36, false, 'Admin', 'GET /notificationLog');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (37, false, 'Admin', 'POST /notificationLog');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (38, false, 'Admin', 'GET /help');

INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (39, false, 'FinTech', 'APPROVAL');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (40, false, 'FinTech', 'NOTIFICATION_LOG');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (41, false, 'FinTech', 'GET /default');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (42, false, 'FinTech', 'GET /lookup');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (43, false, 'FinTech', 'GET /common');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (44, false, 'FinTech', 'POST /common');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (45, false, 'FinTech', 'GET /approval');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (46, false, 'FinTech', 'PUT /approval');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (47, false, 'FinTech', 'POST /approval');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (48, false, 'FinTech', 'GET /notificationLog');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (49, false, 'FinTech', 'POST /notificationLog');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (50, false, 'FinTech', 'GET /account');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (51, false, 'Faces', 'VIEW_ACCOUNT');

INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (52, false, 'Faces', 'GET /lookup');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (53, false, 'Faces', 'GET /common');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (54, false, 'Faces', 'POST /common');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (55, false, 'Faces', 'GET /faces');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (56, false, 'Faces', 'POST /faces');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (57, false, 'Faces', 'PUT /faces');
INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (58, false, 'Faces', 'DELETE /faces');

INSERT INTO opm.role_permission (id, deleted, rolename, action) VALUES (59, false, 'Batch Processing', 'batchProcessingJob');
