/** Scenario 1 calculations **/
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(1, false, to_date('05/30/1978','MM/DD/YYYY'), to_date('02/19/1983','MM/DD/YYYY'), 2, 1, 4, 1, 5861.08, 4, 1, false, null, false);

/** Scenario 2 calculations**/                                                                                                                                                                                                                                                 
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(2, false, to_date('07/10/1966','MM/DD/YYYY'),to_date('10/01/1967','MM/DD/YYYY'), 2, 1, 4, 1, 3925.00,2,2, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(3, false, to_date('05/17/1971','MM/DD/YYYY'),to_date('09/02/1971','MM/DD/YYYY'), 2, 2, 2, 2, 109.89,5,2, false, '11/09/1971', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(4, false, to_date('10/03/1975','MM/DD/YYYY'),to_date('06/01/1976','MM/DD/YYYY'), 2, 2, 2, 2, 504.49,5,2, false, '07/02/1976', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(5, false, to_date('05/13/1981','MM/DD/YYYY'),to_date('09/09/1983','MM/DD/YYYY'), 2, 2, 2, 2, 2459.79,5,2, false, '11/02/1983', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(6, false, to_date('07/27/1987','MM/DD/YYYY'),to_date('09/26/1987','MM/DD/YYYY'), 2, 1, 4, 1, 11802.00,2,2, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(7, false, to_date('09/27/1987','MM/DD/YYYY'),to_date('04/29/1988','MM/DD/YYYY'), 2, 2, 2, 1, 74.02,5,2, false, '07/27/1994', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(8, false, to_date('02/25/1990','MM/DD/YYYY'),to_date('04/30/1994','MM/DD/YYYY'), 2, 2, 2, 1, 571.12,5,2, false, '07/27/1994', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(9, false, to_date('11/30/1999','MM/DD/YYYY'),to_date('01/01/2000','MM/DD/YYYY'), 2, 1, 4, 1, 26998.00,2,2, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(10, false, to_date('01/02/2000','MM/DD/YYYY'),to_date('01/13/2001','MM/DD/YYYY'),2, 1, 4, 1, 28265.00,2,2, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(11, false, to_date('01/14/2001','MM/DD/YYYY'),to_date('07/14/2001','MM/DD/YYYY'),2, 1, 4, 1, 29273.00,2,2, false, null, false);

/** Scenario 3 Calculations **/
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(12, false, to_date('08/01/1976','MM/DD/YYYY'),to_date('10/09/1976','MM/DD/YYYY'),2,1,4,1,7102.00,2, 3, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(13, false, to_date('10/10/1976','MM/DD/YYYY'),to_date('10/08/1977','MM/DD/YYYY'),2,1,4,1,7408.00,2, 3, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(14, false, to_date('10/09/1977','MM/DD/YYYY'),to_date('07/31/1978','MM/DD/YYYY'),2,1,4,1,7930.00,2, 3, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(15, false, to_date('08/01/1978','MM/DD/YYYY'),to_date('10/07/1978','MM/DD/YYYY'),2,1,4,1,8194.00,2, 3, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(16, false, to_date('10/08/1978','MM/DD/YYYY'),to_date('10/06/1979','MM/DD/YYYY'),2,1,4,1,8645.00,2, 3, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(17, false, to_date('10/07/1979','MM/DD/YYYY'),to_date('10/04/1980','MM/DD/YYYY'),2,1,4,1,9250.00,2, 3, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(18, false, to_date('10/05/1980','MM/DD/YYYY'),to_date('11/06/1980','MM/DD/YYYY'),2,1,4,1,10092.00,2, 3, false,null , false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(19, false, to_date('06/04/1981','MM/DD/YYYY'),to_date('01/31/1982','MM/DD/YYYY'),2,1,4,35,125.00,7, 3, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(20, false, to_date('02/01/1982','MM/DD/YYYY'),to_date('11/13/1984','MM/DD/YYYY'),2,1,4,35,175.00,7, 3, false, '12/15/1990', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(21, false, to_date('08/08/1985','MM/DD/YYYY'),to_date('12/31/1987','MM/DD/YYYY'),2,2,2,37,4450.00,5, 3, false, '02/05/1988', false);

/** Scenario 4 Calculations **/
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(22, false, to_date('11/10/1975','MM/DD/YYYY'),to_date('02/11/1976','MM/DD/YYYY'),2,1,8,1,5559.00,2,4,false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(23, false, to_date('02/12/1976','MM/DD/YYYY'),to_date('09/06/1976','MM/DD/YYYY'),2,5,8,1,0.00,1,4,false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(24, false, to_date('06/28/1980','MM/DD/YYYY'),to_date('12/31/1980','MM/DD/YYYY'),2,1,4,38,1951.26,4,4, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(25, false, to_date('01/01/1981','MM/DD/YYYY'),to_date('12/31/1981','MM/DD/YYYY'),2,1,4,38,6458.74,4,4,false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(26, false, to_date('01/01/1982','MM/DD/YYYY'),to_date('09/30/1982','MM/DD/YYYY'),2,1,4,38,3700.43,4,4,false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(27, false, to_date('10/01/1982','MM/DD/YYYY'),to_date('12/31/1982','MM/DD/YYYY'),2,1,4,38,1936.61,4,4, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(28, false, to_date('01/01/1983','MM/DD/YYYY'),to_date('12/31/1983','MM/DD/YYYY'),2,1,4,38,8766.40,4,4, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(29, false, to_date('01/01/1984','MM/DD/YYYY'),to_date('12/31/1984','MM/DD/YYYY'),2,1,4,38,7203.86,4,4, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(30, false, to_date('01/01/1985','MM/DD/YYYY'),to_date('11/08/1985','MM/DD/YYYY'),2,1,4,38,8080.86,4,4, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(31, false, to_date('10/10/1987','MM/DD/YYYY'),to_date('10/15/1990','MM/DD/YYYY'),1,2,2,1,1880.00,5,4, false, to_date('12/01/1990','MM/DD/YYYY'), false);

/** Scenario 5 calculations **/
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(32, false, to_date('05/26/1972','MM/DD/YYYY'),to_date('08/17/1972','MM/DD/YYYY'),2,1,4,14,2.80,3, 5, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(33, false, to_date('07/16/1978','MM/DD/YYYY'),to_date('09/01/1978','MM/DD/YYYY'),2,1,4,14,5.34,3, 5, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(34, false, to_date('09/14/1986','MM/DD/YYYY'),to_date('02/27/1987','MM/DD/YYYY'),2,1,4,14,8.57,3, 5, false, null, false);

/**
 * Scenario 6 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(35, false, to_date('04/07/1986','MM/DD/YYYY'),to_date('07/24/1987','MM/DD/YYYY'),2,1,4,38,7.50,3, 6, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(36, false, to_date('10/11/1990','MM/DD/YYYY'),to_date('07/02/1991','MM/DD/YYYY'),2,1,4,39,11.50,3, 6, false, null, false);

/**
 * Scenario 7 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(37, false, to_date('01/13/1974','MM/DD/YYYY'),to_date('07/16/1988','MM/DD/YYYY'),2,2,2,1,17689.87,5, 7, false, '11/07/1989', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(38, false, to_date('01/13/1974','MM/DD/YYYY'),to_date('07/16/1988','MM/DD/YYYY'),2,2,2,1,500.00,5, 7, false, '02/15/1990', false);

/**
 * Scenario 8 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(39, false, to_date('07/10/1978','MM/DD/YYYY'),to_date('08/31/1983','MM/DD/YYYY'),2,2,2,1,8400.00,5, 8, false, '12/01/1983', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(40, false, to_date('06/06/1987','MM/DD/YYYY'),to_date('01/02/1988','MM/DD/YYYY'),1,1,4,1,13248.00,2, 8, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(41, false, to_date('01/03/1988','MM/DD/YYYY'),to_date('12/31/1988','MM/DD/YYYY'),1,1,4,1,13513.00,2, 8, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(42, false, to_date('01/01/1989','MM/DD/YYYY'),to_date('06/10/1992','MM/DD/YYYY'),1,2,2,1,610.00,5, 8, false, '07/27/1992', false);

/**
 * Scenario 9 calculations. 
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(43, false, to_date('01/19/1986','MM/DD/YYYY'),to_date('02/28/1986','MM/DD/YYYY'),1,1,4,2,9.79,3, 9, false, '12/01/1983', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(44, false, to_date('03/01/1986','MM/DD/YYYY'),to_date('03/14/1986','MM/DD/YYYY'),1,1,4,2,9.79,3, 9, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(45, false, to_date('03/15/1986','MM/DD/YYYY'),to_date('09/15/1990','MM/DD/YYYY'),1,2,2,1,564.97,5, 9, false, '11/15/1991', false);

/**
 * Scenario 10 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(46, false, to_date('05/27/1980','MM/DD/YYYY'),to_date('08/22/1980','MM/DD/YYYY'),1,1,4,1,10049.00,2, 10, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(47, false, to_date('10/27/1982','MM/DD/YYYY'),to_date('09/30/1984','MM/DD/YYYY'),1,1,4,35,175.00,7, 10, false, '10/10/1989', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(48, false, to_date('07/29/1985','MM/DD/YYYY'),to_date('02/28/1986','MM/DD/YYYY'),1,1,4,1,8.54,3, 10, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(49, false, to_date('03/01/1986','MM/DD/YYYY'),to_date('07/28/1986','MM/DD/YYYY'),1,1,4,1,17824.00,2, 10, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(50, false, to_date('10/10/1989','MM/DD/YYYY'),to_date('09/16/1994','MM/DD/YYYY'),1,2,2,1,1438.00,5, 10, false, '02/03/1995', false);

/**
 * Scenario 11 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(51, false, to_date('05/11/1981','MM/DD/YYYY'),to_date('08/16/1981','MM/DD/YYYY'),1,1,4,1,8951.00,2, 11, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(52, false, to_date('08/17/1981','MM/DD/YYYY'),to_date('01/02/1983','MM/DD/YYYY'),1,4,4,1,0.00,1, 11, false, null, false);

/**
 * Scenario 12 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(53, false, to_date('07/13/2003','MM/DD/YYYY'),to_date('01/10/2004','MM/DD/YYYY'),1,1,4,40,41564.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(54, false, to_date('01/11/2004','MM/DD/YYYY'),to_date('03/20/2004','MM/DD/YYYY'),1,1,4,40,42686.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(55, false, to_date('03/21/2004','MM/DD/YYYY'),to_date('07/10/2004','MM/DD/YYYY'),1,1,4,40,53358.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(56, false, to_date('07/11/2004','MM/DD/YYYY'),to_date('07/24/2004','MM/DD/YYYY'),1,1,4,40,54959.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(57, false, to_date('07/25/2004','MM/DD/YYYY'),to_date('01/08/2005','MM/DD/YYYY'),1,1,4,40,59688.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(58, false, to_date('01/09/2005','MM/DD/YYYY'),to_date('07/23/2005','MM/DD/YYYY'),1,1,4,40,61179.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(59, false, to_date('07/24/2005','MM/DD/YYYY'),to_date('01/07/2006','MM/DD/YYYY'),1,1,4,40,63014.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(60, false, to_date('01/08/2006','MM/DD/YYYY'),to_date('02/04/2006','MM/DD/YYYY'),1,1,4,40,64339.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(61, false, to_date('02/05/2006','MM/DD/YYYY'),to_date('08/20/2006','MM/DD/YYYY'),1,1,4,40,68493.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(62, false, to_date('08/21/2006','MM/DD/YYYY'),to_date('01/06/2007','MM/DD/YYYY'),1,1,4,40,80479.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(63, false, to_date('01/07/2007','MM/DD/YYYY'),to_date('02/03/2007','MM/DD/YYYY'),1,1,4,40,82605.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(64, false, to_date('02/04/2007','MM/DD/YYYY'),to_date('10/27/2007','MM/DD/YYYY'),1,1,4,40,85084.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(65, false, to_date('10/28/2007','MM/DD/YYYY'),to_date('01/05/2008','MM/DD/YYYY'),1,1,4,40,90576.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(66, false, to_date('01/06/2008','MM/DD/YYYY'),to_date('10/25/2008','MM/DD/YYYY'),1,1,4,40,94644.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(67, false, to_date('10/26/2008','MM/DD/YYYY'),to_date('01/03/2009','MM/DD/YYYY'),1,1,4,40,97483.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(68, false, to_date('01/04/2009','MM/DD/YYYY'),to_date('10/24/2009','MM/DD/YYYY'),1,1,4,40,102143.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(69, false, to_date('10/25/2009','MM/DD/YYYY'),to_date('01/02/2010','MM/DD/YYYY'),1,1,4,40,105208.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(70, false, to_date('01/03/2010','MM/DD/YYYY'),to_date('10/23/2010','MM/DD/YYYY'),1,1,4,40,107756.00,2, 12, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(71, false, to_date('10/24/2010','MM/DD/YYYY'),to_date('10/22/2011','MM/DD/YYYY'),1,1,4,40,110989.00,2, 12, false, null, false);

/**
 * Scenario 13 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(72, false, to_date('09/30/1974','MM/DD/YYYY'),to_date('08/08/1975','MM/DD/YYYY'),2,1,4,35,75.00,7, 13, false, '10/01/1995', false);

/**
 * Scenario 14 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(73, false, to_date('02/01/1972','MM/DD/YYYY'),to_date('06/02/1974','MM/DD/YYYY'),2,1,4,35,1298.00,4,14, false, '07/15/1975', false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(74, false, to_date('07/07/2007','MM/DD/YYYY'),to_date('08/07/2009','MM/DD/YYYY'),1,1,4,35,2500.00,4,14, false, '10/10/2010', false);

/**
 * Scenario 15 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(75, false, to_date('05/22/1977','MM/DD/YYYY'),to_date('07/30/1977','MM/DD/YYYY'),2,1,4,1,6572.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(76, false, to_date('07/31/1977','MM/DD/YYYY'),to_date('09/30/1977','MM/DD/YYYY'),2,1,4,1,7408.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(77, false, to_date('04/23/1978','MM/DD/YYYY'),to_date('10/07/1978','MM/DD/YYYY'),2,1,4,1,7930.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(78, false, to_date('10/08/1978','MM/DD/YYYY'),to_date('12/03/1978','MM/DD/YYYY'),2,1,4,1,8366.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(79, false, to_date('04/02/1979','MM/DD/YYYY'),to_date('10/06/1979','MM/DD/YYYY'),2,1,4,1,9391.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(80, false, to_date('10/07/1979','MM/DD/YYYY'),to_date('10/20/1979','MM/DD/YYYY'),2,1,4,1,10049.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(81, false, to_date('10/21/1979','MM/DD/YYYY'),to_date('12/15/1979','MM/DD/YYYY'),2,1,4,1,11243.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(82, false, to_date('04/14/1980','MM/DD/YYYY'),to_date('10/04/1980','MM/DD/YYYY'),2,1,4,1,11243.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(83, false, to_date('10/05/1980','MM/DD/YYYY'),to_date('12/13/1980','MM/DD/YYYY'),2,1,4,1,12266.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(84, false, to_date('04/05/1981','MM/DD/YYYY'),to_date('10/03/1981','MM/DD/YYYY'),2,1,4,1,12266.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(85, false, to_date('10/04/1981','MM/DD/YYYY'),to_date('11/28/1981','MM/DD/YYYY'),2,1,4,1,12854.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(86, false, to_date('04/04/1982','MM/DD/YYYY'),to_date('09/30/1982','MM/DD/YYYY'),2,1,4,1,12854.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(87, false, to_date('10/01/1982','MM/DD/YYYY'),to_date('10/02/1982','MM/DD/YYYY'),2,1,4,1,12854.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(88, false, to_date('10/03/1982','MM/DD/YYYY'),to_date('01/08/1983','MM/DD/YYYY'),2,1,4,1,13369.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(89, false, to_date('04/03/1983','MM/DD/YYYY'),to_date('12/24/1983','MM/DD/YYYY'),2,1,4,1,13369.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(90, false, to_date('04/01/1984','MM/DD/YYYY'),to_date('12/22/1984','MM/DD/YYYY'),2,1,4,1,13837.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(91, false, to_date('03/31/1985','MM/DD/YYYY'),to_date('11/09/1985','MM/DD/YYYY'),2,1,4,1,14390.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(92, false, to_date('11/10/1985','MM/DD/YYYY'),to_date('12/07/1985','MM/DD/YYYY'),2,1,4,1,17824.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(93, false, to_date('12/08/1985','MM/DD/YYYY'),to_date('02/01/1986','MM/DD/YYYY'),2,5,8,1,0.00,1, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(94, false, to_date('02/02/1986','MM/DD/YYYY'),to_date('01/03/1987','MM/DD/YYYY'),2,1,4,1,17824.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(95, false, to_date('01/04/1987','MM/DD/YYYY'),to_date('02/28/1987','MM/DD/YYYY'),2,5,8,1,0.00,1, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(96, false, to_date('03/01/1987','MM/DD/YYYY'),to_date('01/02/1988','MM/DD/YYYY'),2,1,4,1,18726.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(97, false, to_date('01/03/1988','MM/DD/YYYY'),to_date('01/30/1988','MM/DD/YYYY'),2,1,4,1,18726.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(98, false, to_date('01/31/1988','MM/DD/YYYY'),to_date('02/27/1988','MM/DD/YYYY'),2,5,8,1,0.00,1, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(99, false, to_date('02/28/1988','MM/DD/YYYY'),to_date('12/09/1988','MM/DD/YYYY'),2,1,4,1,18726.00,2, 15, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(100, false,to_date('12/10/1988','MM/DD/YYYY'),to_date('12/31/1988','MM/DD/YYYY'),2,5,8,1,0.00,1, 15, true, null, false);

/**
 * Scenario 16 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(101, false, to_date('01/01/1989','MM/DD/YYYY'),to_date('02/25/1989','MM/DD/YYYY'),2,5,8,1,0.00,1, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(102, false, to_date('02/26/1989','MM/DD/YYYY'),to_date('11/09/1989','MM/DD/YYYY'),2,1,4,1,19493.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(103, false, to_date('03/11/1990','MM/DD/YYYY'),to_date('12/01/1990','MM/DD/YYYY'),2,1,4,1,20195.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(104, false, to_date('12/02/1990','MM/DD/YYYY'),to_date('02/23/1991','MM/DD/YYYY'),2,5,8,1,0.00,1, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(105, false, to_date('02/24/1991','MM/DD/YYYY'),to_date('11/30/1991','MM/DD/YYYY'),2,1,4,1,21023.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(106, false, to_date('12/01/1991','MM/DD/YYYY'),to_date('12/15/1991','MM/DD/YYYY'),2,5,8,1,0.00,1, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(107, false, to_date('04/13/1992','MM/DD/YYYY'),to_date('11/14/1992','MM/DD/YYYY'),2,1,4,1,21906.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(108, false, to_date('04/04/1993','MM/DD/YYYY'),to_date('05/15/1993','MM/DD/YYYY'),2,1,4,1,18340.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(109, false, to_date('05/16/1993','MM/DD/YYYY'),to_date('12/25/1993','MM/DD/YYYY'),2,1,4,1,22717.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(110, false, to_date('03/06/1994','MM/DD/YYYY'),to_date('01/07/1995','MM/DD/YYYY'),2,1,4,1,23419.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(111, false, to_date('01/08/1995','MM/DD/YYYY'),to_date('01/21/1995','MM/DD/YYYY'),2,1,4,1,24038.00,2, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(112, false, to_date('01/22/1995','MM/DD/YYYY'),to_date('04/15/1995','MM/DD/YYYY'),2,5,8,1,0.00,1, 16, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(113, false, to_date('04/16/1995','MM/DD/YYYY'),to_date('10/27/1995','MM/DD/YYYY'),2,1,4,1,24038.00,2, 16, true, null, false);

/**
 * Scenario 17 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(114, false, to_date('05/22/1977','MM/DD/YYYY'),to_date('07/30/1977','MM/DD/YYYY'),1,1,4,1,6572.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(115, false, to_date('07/31/1977','MM/DD/YYYY'),to_date('09/30/1977','MM/DD/YYYY'),1,1,4,1,7408.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(116, false, to_date('04/23/1978','MM/DD/YYYY'),to_date('10/07/1978','MM/DD/YYYY'),1,1,4,1,7930.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(117, false, to_date('10/08/1978','MM/DD/YYYY'),to_date('12/03/1978','MM/DD/YYYY'),1,1,4,1,8366.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(118, false, to_date('04/02/1979','MM/DD/YYYY'),to_date('10/06/1979','MM/DD/YYYY'),1,1,4,1,9391.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(119, false, to_date('10/07/1979','MM/DD/YYYY'),to_date('10/20/1979','MM/DD/YYYY'),1,1,4,1,10049.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(120, false, to_date('10/21/1979','MM/DD/YYYY'),to_date('12/15/1979','MM/DD/YYYY'),1,1,4,1,11243.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(121, false, to_date('04/14/1980','MM/DD/YYYY'),to_date('10/04/1980','MM/DD/YYYY'),1,1,4,1,11243.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(122, false, to_date('10/05/1980','MM/DD/YYYY'),to_date('12/13/1980','MM/DD/YYYY'),1,1,4,1,12266.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(123, false, to_date('04/05/1981','MM/DD/YYYY'),to_date('10/03/1981','MM/DD/YYYY'),1,1,4,1,12266.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(124, false, to_date('10/04/1981','MM/DD/YYYY'),to_date('11/28/1981','MM/DD/YYYY'),1,1,4,1,12854.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(125, false, to_date('04/04/1982','MM/DD/YYYY'),to_date('09/30/1982','MM/DD/YYYY'),1,1,4,1,12854.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(126, false, to_date('10/01/1982','MM/DD/YYYY'),to_date('10/02/1982','MM/DD/YYYY'),1,1,4,1,12854.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(127, false, to_date('10/03/1982','MM/DD/YYYY'),to_date('01/08/1983','MM/DD/YYYY'),1,1,4,1,13369.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(128, false, to_date('04/03/1983','MM/DD/YYYY'),to_date('12/24/1983','MM/DD/YYYY'),1,1,4,1,13369.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(129, false, to_date('04/01/1984','MM/DD/YYYY'),to_date('12/22/1984','MM/DD/YYYY'),1,1,4,1,13837.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(130, false, to_date('03/31/1985','MM/DD/YYYY'),to_date('11/09/1985','MM/DD/YYYY'),1,1,4,1,14390.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(131, false, to_date('11/10/1985','MM/DD/YYYY'),to_date('12/07/1985','MM/DD/YYYY'),1,1,4,1,17824.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(132, false, to_date('12/08/1985','MM/DD/YYYY'),to_date('02/01/1986','MM/DD/YYYY'),1,5,8,1,0.00,1, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(133, false, to_date('02/02/1986','MM/DD/YYYY'),to_date('01/03/1987','MM/DD/YYYY'),1,1,4,1,17824.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(134, false, to_date('01/04/1987','MM/DD/YYYY'),to_date('02/28/1987','MM/DD/YYYY'),1,5,8,1,0.00,1, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(135, false, to_date('03/01/1987','MM/DD/YYYY'),to_date('01/02/1988','MM/DD/YYYY'),1,1,4,1,18726.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(136, false, to_date('01/03/1988','MM/DD/YYYY'),to_date('01/30/1988','MM/DD/YYYY'),1,1,4,1,18726.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(137, false, to_date('01/31/1988','MM/DD/YYYY'),to_date('02/27/1988','MM/DD/YYYY'),1,5,8,1,0.00,1, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(138, false, to_date('02/28/1988','MM/DD/YYYY'),to_date('12/09/1988','MM/DD/YYYY'),1,1,4,1,18726.00,2, 17, true, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(139, false, to_date('12/10/1988','MM/DD/YYYY'),to_date('12/31/1988','MM/DD/YYYY'),1,5,8,1,0.00,1, 17, true, null, false);


/**
 * Scenario 18 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(140, false, to_date('05/07/1985','MM/DD/YYYY'),to_date('02/28/1986','MM/DD/YYYY'),2,1,4,15,12862.00,2, 18, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(141, false, to_date('01/01/1987','MM/DD/YYYY'),to_date('01/02/1988','MM/DD/YYYY'),2,1,4,15,13248.00,2, 18, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(142, false, to_date('01/03/1988','MM/DD/YYYY'),to_date('12/31/1988','MM/DD/YYYY'),2,1,4,15,13513.00,2, 18, false, null, false);

/**
 * Scenario 19 calculations.
 */
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(143, false, to_date('05/20/1980','MM/DD/YYYY'),to_date('06/01/1981','MM/DD/YYYY'),2,1,4,14,3.91,3, 19, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(144, false, to_date('05/06/1985','MM/DD/YYYY'),to_date('10/01/1986','MM/DD/YYYY'),2,1,4,14,5.05,3, 19, false, null, false);
INSERT INTO opm.calculation(id, deleted, begin_date, end_date, retirement_type_id, period_type_id, appointment_type_id, service_type_id, amount, pay_type_id, calculation_version_id, conner_case, interest_accrual_date, frozen) VALUES(145, false, to_date('10/02/1986','MM/DD/YYYY'),to_date('12/31/1987','MM/DD/YYYY'),2,1,4,1,7.35,3, 19, false, null, false);



ALTER SEQUENCE opm.calculation_id_seq RESTART WITH 146;