
<div class="viewReportWrapper isHidden" data-report-name="ResolvedSuspenseHistory">
	<div class="reportPageReportWrapper report-ResolvedSuspenseHistory isHidden">
		<div class="reportTitleArea">
			<p class="reportDate">6/7/2013</p>
			<h1>Resolved Suspense History</h1>
		</div>
		<div class="reportTblWrapper">
			<table width="100%" cellspacing="0" cellpadding="0" border="0"
				class="blackTbl reportRealTable">
				<colgroup>
					<col class="col0" />
					<col class="col1" />
					<col class="col2" />
					<col class="col3" />
					<col class="col4" />
					<col class="col5" />
					<col class="col6" />
					<col class="col7" />
					<col class="col8" />
				</colgroup>
				<tbody></tbody>
			</table>
			<table class="reportTemplateTable isHidden">
				<tbody>
					<tr class="tGroupRow">
						<td colspan="9" class="boldTxt">Annuity - Complete</td>
					</tr>
					<tr class="tHeadRow">
						<td>Bat</td>
						<td>Blk</td>
						<td>Seq</td>
						<td class="aCenter">CSD</td>
						<td>Birth Date</td>
						<td class="aRight">Amount</td>
						<td class="aRight">Deposited Date</td>
						<td>Technian</td>
						<td>Note</td>
					</tr>
					<tr class="tDataRow">
						<td>133</td>
						<td>01</td>
						<td>04</td>
						<td class="aCenter">11111111</td>
						<td>01/01/1800</td>
						<td class="aRight">$755.00</td>
						<td class="aRight">04/14/2006</td>
						<td>X XXX42</td>
						<td>This was not a service credit payment but an annuity
							payment. Itis resolve as annuity and the paperwork was mannualy
							generated by Katina Whitley.</td>
					</tr>
					<tr class="sepRow">
						<td colspan="9">&nbsp;</td>
					</tr>
				</tbody>
			</table>
			<div class="doubleSepLine"></div>
			<img src="#"
				alt="Count of Resolved Suspense Items" class="reportChart" />
		</div>
	</div>
</div>
